### ISSUE TITLE
Create user details page

### ISSUE THREAD

**Issue by Jacob-Levitan** [z-cohn/tic-tac-toe#15]
Use jwt to verify the user

Display user data:
- Username
- email
- wins
- losses

Username is editable only by that user, must be unique.

Button to delete user, with a popup box to confirm.

**Comment by z-cohn** [comment]
Maybe want to keep (even if not displayed) - date created, date updated

**Comment by Jacob-Levitan** [comment]
Server should NOT return the mongo ID or the hashed password
https://www.freecodecamp.org/news/build-a-restful-api-using-node-express-and-mongodb/
